name: anylinejs
description: A Dart API for anylinejs.
version: 0.1.0-dev.1
repository: https://github.com/daniellampl/anylinejs.dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  js: ^0.6.4

dev_dependencies:
  lints: ^2.0.0
